// ignore_for_file: prefer_const_constructors, prefer_const_literals_to_create_immutables
/// Bias report — Fixmyitch minimal.
library;

import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../models/bias_report.dart';
import '../models/grievance.dart';
import '../providers/analysis_provider.dart';
import '../services/api_service.dart';
import '../utils/theme.dart';
import '../widgets/loading_overlay.dart';

class BiasReportScreen extends ConsumerStatefulWidget {
  final String analysisId;
  const BiasReportScreen({super.key, required this.analysisId});

  @override
  ConsumerState<BiasReportScreen> createState() => _BiasReportScreenState();
}

class _BiasReportScreenState extends ConsumerState<BiasReportScreen>
    with TickerProviderStateMixin {
  BiasReport? _report;
  bool _isLoading = true;
  bool _isGeneratingPdf = false;
  String? _error;
  late AnimationController _gaugeCtrl;
  final List<AnimationController> _sectionCtrls = [];

  @override
  void initState() {
    super.initState();
    _gaugeCtrl = AnimationController(
        duration: const Duration(milliseconds: 900), vsync: this);
    _loadReport();
  }

  Future<void> _loadReport() async {
    final analysisState = ref.read(analysisProvider);
    if (analysisState.report != null) {
      if (mounted) {
        setState(() {
          _report = analysisState.report;
          _isLoading = false;
          _gaugeCtrl.forward();
        });
      }
      return;
    }

    try {
      final report =
          await ApiService.instance.getAnalysisReport(widget.analysisId);
      if (mounted) {
        setState(() {
          _report = report;
          _isLoading = false;
          _gaugeCtrl.forward();
        });
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _error = e.toString();
          _isLoading = false;
        });
      }
    }
  }

  Future<void> _downloadGrievancePdf() async {
    setState(() => _isGeneratingPdf = true);
    try {
      final data = await ApiService.instance.getGrievanceData(widget.analysisId);
      await _performPdfDownload(data);
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Failed to generate PDF: $e'),
            backgroundColor: AppColors.error,
          ),
        );
      }
    } finally {
      if (mounted) setState(() => _isGeneratingPdf = false);
    }
  }

  Future<void> _performPdfDownload(GrievanceData data) async {
    try {
      await Printing.layoutPdf(
        name: 'fairterms_grievance_${widget.analysisId}.pdf',
        onLayout: (PdfPageFormat format) async {
          final doc = pw.Document();
          doc.addPage(
            pw.MultiPage(
              pageFormat: format,
              margin: const pw.EdgeInsets.all(48),
              build: (pw.Context ctx) => [
                pw.Text(
                  data.grievanceLetter.subject,
                  style: pw.TextStyle(
                    fontSize: 18,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.SizedBox(height: 24),
                pw.Text(
                  data.grievanceLetter.body,
                  style: const pw.TextStyle(fontSize: 11, lineSpacing: 4),
                ),
                pw.SizedBox(height: 48),
                pw.Divider(thickness: 1, color: PdfColors.grey300),
                pw.SizedBox(height: 12),
                pw.Text(
                  'Generated by FairTerms AI Analysis • ${DateFormat('dd MMM yyyy').format(DateTime.now())}',
                  style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
                ),
              ],
            ),
          );
          return doc.save();
        },
      );
    } catch (e) {
      debugPrint('PDF layout error: $e');
    }
  }

  @override
  void dispose() {
    _gaugeCtrl.dispose();
    for (final ctrl in _sectionCtrls) {
      ctrl.dispose();
    }
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (_isLoading) {
      return Scaffold(
        backgroundColor: AppColors.background,
        body: Center(
          child: CircularProgressIndicator(color: AppColors.primary),
        ),
      );
    }

    if (_error != null) {
      return Scaffold(
        backgroundColor: AppColors.background,
        body: Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Icon(Icons.error_outline, color: AppColors.error, size: 48),
              SizedBox(height: 16),
              Text('Failed to load report',
                  style:
                      GoogleFonts.fraunces(fontSize: 18, color: AppColors.ink)),
              SizedBox(height: 8),
              Text(_error!,
                  style: GoogleFonts.inter(color: AppColors.inkMuted)),
              SizedBox(height: 16),
              ElevatedButton(
                onPressed: () {
                  setState(() {
                    _isLoading = true;
                    _error = null;
                  });
                  _loadReport();
                },
                child: Text('Retry'),
              ),
            ],
          ),
        ),
      );
    }

    final report = _report!;
    final score = report.overallFairnessScore.toInt();
    final isSevere = score < 41;
    final isModerate = score >= 41 && score < 71;

    Color eyebrowColor = AppColors.primary;
    String eyebrowLabel = 'Fair terms';
    if (isSevere) {
      eyebrowColor = AppColors.error;
      eyebrowLabel = 'Severe bias detected';
    } else if (isModerate) {
      eyebrowColor = AppColors.warning;
      eyebrowLabel = 'Moderate bias detected';
    }
    return LoadingOverlay(
      isLoading: _isGeneratingPdf,
      message: 'Generating PDF document...',
      child: Scaffold(
        backgroundColor: AppColors.background,
        body: Column(
          children: [
            _TopBar(),
            Expanded(
              child: SingleChildScrollView(
                child: Column(
                  children: [
                    Padding(
                      padding: EdgeInsets.symmetric(horizontal: 40, vertical: 24),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            'Dashboard  /  Analyses  /  ${report.analysisId}',
                            style: GoogleFonts.inter(
                              fontSize: 12,
                              color: AppColors.inkFaint,
                              letterSpacing: 0.02,
                            ),
                          ),
                          SizedBox(height: 20),
                          Row(
                            crossAxisAlignment: CrossAxisAlignment.end,
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              Expanded(
                                child: Column(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Text(
                                      eyebrowLabel,
                                      style: GoogleFonts.inter(
                                        fontSize: 11,
                                        fontWeight: FontWeight.w500,
                                        letterSpacing: 0.14,
                                        color: eyebrowColor,
                                      ),
                                    ),
                                    SizedBox(height: 14),
                                    Text(
                                      report.analysisId,
                                      style: GoogleFonts.fraunces(
                                        fontSize: 56,
                                        fontWeight: FontWeight.w300,
                                        letterSpacing: -0.03,
                                        color: AppColors.ink,
                                        height: 1.02,
                                      ),
                                    ),
                                    SizedBox(height: 16),
                                    Text(
                                      '${report.explanation.paragraphs.isNotEmpty ? report.explanation.paragraphs.first : "Analysis from ${report.analysisId}"} • Analysed on ${_fmtDate(DateTime.now())}',
                                      style: GoogleFonts.inter(
                                        fontSize: 14,
                                        color: AppColors.inkMuted,
                                        height: 1.55,
                                      ),
                                      maxLines: 3,
                                    ),
                                  ],
                                ),
                              ),
                              Row(
                                mainAxisSize: MainAxisSize.min,
                                children: [
                                  _GhostBtn(
                                    label: 'Share',
                                    onPressed: () {
                                      final url = Uri.base
                                          .resolve('/analysis/${widget.analysisId}/report')
                                          .toString();
                                      Clipboard.setData(ClipboardData(text: url));
                                      ScaffoldMessenger.of(context).showSnackBar(
                                        const SnackBar(content: Text('Report link copied to clipboard')),
                                      );
                                    },
                                  ),
                                  SizedBox(width: 8),
                                  _SolidBtn(
                                    label: 'Download PDF',
                                    onPressed: _downloadGrievancePdf,
                                  ),
                                ],
                              ),
                            ],
                          ),
                          Divider(
                            color: AppColors.outline,
                            height: 64,
                            thickness: 1,
                          ),
                          _HeroSection(
                            score: score,
                            eyebrowColor: eyebrowColor,
                            verdict: report.explanation.headline,
                            description: report.explanation.paragraphs.length > 1
                                ? report.explanation.paragraphs[1]
                                : report.explanation.paragraphs.isNotEmpty
                                    ? report.explanation.paragraphs[0]
                                    : 'Analysis computed.',
                            factors: report.biasFactors,
                            gaugeCtrl: _gaugeCtrl,
                          ),
                          SizedBox(height: 64),
                          _FactorSection(factors: report.biasFactors),
                          SizedBox(height: 64),
                          _BenchmarkSection(
                              benchmarks: report.benchmarkComparison),
                          SizedBox(height: 64),
                          if (report.interestCalculation != null)
                            _InterestSection(
                                interest: report.interestCalculation!),
                          if (report.interestCalculation != null)
                            SizedBox(height: 64),
                          if (report.taxAlert != null)
                            _TaxAlertSection(alert: report.taxAlert!),
                          if (report.taxAlert != null) SizedBox(height: 64),
                          _ActionSection(
                            analysisId: widget.analysisId,
                            onDownloadPdf: _downloadGrievancePdf,
                          ),
                          SizedBox(height: 80),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  String _fmtDate(DateTime dt) => DateFormat('dd MMMM yyyy').format(dt);
}

// --- TOP BAR ---

class _TopBar extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      padding: EdgeInsets.symmetric(horizontal: 40, vertical: 18),
      decoration: BoxDecoration(
        border: Border(
          bottom: BorderSide(color: AppColors.outline, width: 1),
        ),
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Row(
            children: [
              Container(
                width: 8,
                height: 8,
                decoration: BoxDecoration(
                  shape: BoxShape.circle,
                  color: AppColors.primary,
                ),
              ),
              SizedBox(width: 10),
              Text(
                'FairTerms',
                style: GoogleFonts.fraunces(
                  fontSize: 20,
                  fontWeight: FontWeight.w400,
                  letterSpacing: -0.02,
                  color: AppColors.ink,
                ),
              ),
            ],
          ),
          InkWell(
            onTap: () => context.pop(),
            child: Row(
              children: [
                Icon(Icons.arrow_back, size: 14, color: AppColors.inkFaint),
                SizedBox(width: 6),
                Text(
                  'Back to dashboard',
                  style: GoogleFonts.inter(
                    fontSize: 13,
                    color: AppColors.inkFaint,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

// --- HERO SECTION ---

class _HeroSection extends StatelessWidget {
  final int score;
  final Color eyebrowColor;
  final String verdict;
  final String description;
  final List<BiasFactor> factors;
  final AnimationController gaugeCtrl;

  const _HeroSection({
    required this.score,
    required this.eyebrowColor,
    required this.verdict,
    required this.description,
    required this.factors,
    required this.gaugeCtrl,
  });

  @override
  Widget build(BuildContext context) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.center,
      children: [
        _Gauge(
          score: score,
          color: eyebrowColor,
          animation: gaugeCtrl,
        ),
        SizedBox(width: 48),
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                verdict,
                style: GoogleFonts.fraunces(
                  fontSize: 36,
                  fontWeight: FontWeight.w400,
                  letterSpacing: -0.02,
                  color: eyebrowColor,
                ),
              ),
              SizedBox(height: 10),
              Text(
                description,
                style: GoogleFonts.inter(
                  fontSize: 15,
                  color: AppColors.inkMuted,
                  height: 1.6,
                ),
                maxLines: 5,
              ),
              SizedBox(height: 18),
              Wrap(
                spacing: 8,
                children: factors.take(3).map((f) {
                  return Container(
                    padding: EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                    decoration: BoxDecoration(
                      border: Border.all(color: AppColors.outline, width: 1),
                      borderRadius: BorderRadius.circular(999),
                      color: AppColors.background,
                    ),
                    child: Text(
                      f.factor,
                      style: GoogleFonts.inter(
                        fontSize: 12,
                        color: AppColors.inkMuted,
                      ),
                    ),
                  );
                }).toList(),
              ),
            ],
          ),
        ),
      ],
    );
  }
}

class _Gauge extends StatefulWidget {
  final int score;
  final Color color;
  final AnimationController animation;

  const _Gauge({
    required this.score,
    required this.color,
    required this.animation,
  });

  @override
  State<_Gauge> createState() => _GaugeState();
}

class _GaugeState extends State<_Gauge> {
  late Animation<double> _scoreAnim;

  @override
  void initState() {
    super.initState();
    _scoreAnim = Tween<double>(begin: 0, end: widget.score.toDouble()).animate(
        CurvedAnimation(parent: widget.animation, curve: Curves.easeOut));
  }

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: 240,
      height: 240,
      child: Stack(
        alignment: Alignment.center,
        children: [
          AnimatedBuilder(
            animation: _scoreAnim,
            builder: (ctx, _) {
              return CustomPaint(
                size: Size(240, 240),
                painter: _GaugePainter(
                  score: _scoreAnim.value,
                  color: widget.color,
                ),
              );
            },
          ),
          Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              AnimatedBuilder(
                animation: _scoreAnim,
                builder: (ctx, _) {
                  return Text(
                    '${_scoreAnim.value.toInt()}',
                    style: GoogleFonts.fraunces(
                      fontSize: 76,
                      fontWeight: FontWeight.w300,
                      letterSpacing: -0.04,
                      color: AppColors.ink,
                    ),
                  );
                },
              ),
              SizedBox(height: 6),
              Text(
                '/ 100 · ${widget.color == AppColors.error ? 'severe' : widget.color == AppColors.warning ? 'moderate' : 'fair'}',
                style: GoogleFonts.inter(
                  fontSize: 11,
                  letterSpacing: 0.12,
                  color: AppColors.inkFaint,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

class _GaugePainter extends CustomPainter {
  final double score;
  final Color color;

  _GaugePainter({required this.score, required this.color});

  @override
  void paint(Canvas canvas, Size size) {
    final center = Offset(size.width / 2, size.height / 2);
    const radius = 100.0;
    const strokeWidth = 14.0;

    // Track (cream)
    final trackPaint = Paint()
      ..style = PaintingStyle.stroke
      ..strokeWidth = strokeWidth
      ..strokeCap = StrokeCap.round
      ..color = AppColors.outline;

    canvas.drawCircle(center, radius, trackPaint);

    // Arc (colored)
    final arcPaint = Paint()
      ..style = PaintingStyle.stroke
      ..strokeWidth = strokeWidth
      ..strokeCap = StrokeCap.round
      ..color = color;

    final sweepAngle = 2 * math.pi * (score.clamp(0, 100) / 100);
    canvas.drawArc(
      Rect.fromCircle(center: center, radius: radius),
      -math.pi / 2,
      sweepAngle,
      false,
      arcPaint,
    );
  }

  @override
  bool shouldRepaint(_GaugePainter old) =>
      old.score != score || old.color != color;
}

// --- FACTOR SECTION ---

class _FactorSection extends StatelessWidget {
  final List<BiasFactor> factors;

  const _FactorSection({required this.factors});

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          "What's driving the score",
          style: GoogleFonts.fraunces(
            fontSize: 24,
            fontWeight: FontWeight.w400,
            letterSpacing: -0.02,
            color: AppColors.ink,
          ),
        ),
        SizedBox(height: 20),
        Container(
          padding: EdgeInsets.all(28),
          decoration: BoxDecoration(
            border: Border.all(color: AppColors.outline, width: 1),
            borderRadius: BorderRadius.circular(12),
            color: AppColors.background,
          ),
          child: Column(
            children: factors.isEmpty
                ? [
                    Text(
                      'No factors flagged.',
                      style: GoogleFonts.inter(color: AppColors.inkFaint),
                    ),
                  ]
                : factors.asMap().entries.map((e) {
                    final f = e.value;
                    final isLast = e.key == factors.length - 1;
                    final weight = (f.impactScore * 25).toInt();

                    Color barColor = AppColors.primary;
                    if (f.impactScore > 0.66) {
                      barColor = AppColors.error;
                    } else if (f.impactScore > 0.33) {
                      barColor = AppColors.warning;
                    }

                    return Column(
                      children: [
                        Padding(
                          padding: EdgeInsets.symmetric(vertical: 20),
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Row(
                                mainAxisAlignment:
                                    MainAxisAlignment.spaceBetween,
                                children: [
                                  Text(
                                    f.factor,
                                    style: GoogleFonts.fraunces(
                                      fontSize: 18,
                                      fontWeight: FontWeight.w400,
                                      letterSpacing: -0.01,
                                      color: AppColors.ink,
                                    ),
                                  ),
                                  Text(
                                    'weight $weight%',
                                    style: GoogleFonts.jetBrainsMono(
                                      fontSize: 11,
                                      color: AppColors.inkFaint,
                                    ),
                                  ),
                                ],
                              ),
                              SizedBox(height: 6),
                              Text(
                                f.detail,
                                style: GoogleFonts.inter(
                                  fontSize: 13,
                                  color: AppColors.inkMuted,
                                  height: 1.6,
                                ),
                              ),
                              SizedBox(height: 14),
                              ClipRRect(
                                borderRadius: BorderRadius.circular(4),
                                child: Container(
                                  height: 6,
                                  color: AppColors.surface,
                                  child: FractionallySizedBox(
                                    widthFactor: f.impactScore.clamp(0, 1),
                                    alignment: Alignment.centerLeft,
                                    child: Container(color: barColor),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                        if (!isLast)
                          Divider(
                            color: AppColors.outline,
                            height: 1,
                            thickness: 1,
                          ),
                      ],
                    );
                  }).toList(),
          ),
        ),
      ],
    );
  }
}

// --- BENCHMARK SECTION ---

class _BenchmarkSection extends StatelessWidget {
  final BenchmarkComparison benchmarks;

  const _BenchmarkSection({required this.benchmarks});

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          'How you stack up',
          style: GoogleFonts.fraunces(
            fontSize: 24,
            fontWeight: FontWeight.w400,
            letterSpacing: -0.02,
            color: AppColors.ink,
          ),
        ),
        SizedBox(height: 20),
        Container(
          padding: EdgeInsets.all(28),
          decoration: BoxDecoration(
            border: Border.all(color: AppColors.outline, width: 1),
            borderRadius: BorderRadius.circular(12),
            color: AppColors.background,
          ),
          child: Column(
            children: [
              _BenchRow(
                label: 'Top quartile peers',
                pct: 0.82,
                val: '82',
              ),
              Divider(
                color: AppColors.outline,
                height: 1,
                thickness: 1,
              ),
              _BenchRow(
                label: 'State median',
                pct: benchmarks.peerMedianDays / 100,
                val: '${benchmarks.peerMedianDays.round()}',
              ),
              Divider(
                color: AppColors.outline,
                height: 1,
                thickness: 1,
              ),
              _BenchRow(
                label: 'This contract',
                pct: benchmarks.yourTermsDays / 100,
                val: '${benchmarks.yourTermsDays}',
                isYou: true,
              ),
              Divider(
                color: AppColors.outline,
                height: 1,
                thickness: 1,
              ),
              _BenchRow(
                label: 'Bottom quartile',
                pct: 0.28,
                val: '28',
              ),
            ],
          ),
        ),
      ],
    );
  }
}

class _BenchRow extends StatelessWidget {
  final String label;
  final double pct;
  final String val;
  final bool isYou;

  const _BenchRow({
    required this.label,
    required this.pct,
    required this.val,
    this.isYou = false,
  });

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.symmetric(vertical: 12),
      child: Row(
        children: [
          SizedBox(
            width: 140,
            child: Text(
              label,
              style: GoogleFonts.inter(
                fontSize: 13,
                color: AppColors.inkMuted,
              ),
            ),
          ),
          SizedBox(width: 16),
          Expanded(
            child: ClipRRect(
              borderRadius: BorderRadius.circular(4),
              child: Container(
                height: 6,
                color: AppColors.surface,
                child: FractionallySizedBox(
                  widthFactor: pct.clamp(0, 1),
                  alignment: Alignment.centerLeft,
                  child: Container(
                    color: isYou ? AppColors.ink : AppColors.primary,
                  ),
                ),
              ),
            ),
          ),
          SizedBox(width: 16),
          SizedBox(
            width: 64,
            child: Text(
              val,
              textAlign: TextAlign.right,
              style: GoogleFonts.jetBrainsMono(
                fontSize: 12,
                color: AppColors.inkMuted,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

// --- INTEREST SECTION ---

class _InterestSection extends StatelessWidget {
  final InterestCalculation interest;

  const _InterestSection({required this.interest});

  @override
  Widget build(BuildContext context) {
    final fmtInr = NumberFormat.decimalPattern('en_IN');

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          'Interest you\'re owed (MSMED §16)',
          style: GoogleFonts.fraunces(
            fontSize: 24,
            fontWeight: FontWeight.w400,
            letterSpacing: -0.02,
            color: AppColors.ink,
          ),
        ),
        SizedBox(height: 20),
        Container(
          padding: EdgeInsets.all(28),
          decoration: BoxDecoration(
            border: Border.all(color: AppColors.outline, width: 1),
            borderRadius: BorderRadius.circular(12),
            color: AppColors.background,
          ),
          child: GridView.count(
            crossAxisCount: 4,
            mainAxisSpacing: 16,
            crossAxisSpacing: 16,
            shrinkWrap: true,
            physics: NeverScrollableScrollPhysics(),
            childAspectRatio: 1.6,
            children: [
              _CalcCard(
                label: 'Principal',
                value: '₹${fmtInr.format(interest.principalInr)}',
              ),
              _CalcCard(
                label: 'Delay',
                value: '${interest.delayDays} days',
              ),
              _CalcCard(
                label: 'RBI + 3%',
                value: '${interest.applicableRate.toStringAsFixed(2)}%',
              ),
              _CalcCard(
                label: 'Interest owed',
                value: '₹${fmtInr.format(interest.compoundInterestInr)}',
                isTotal: true,
              ),
            ],
          ),
        ),
      ],
    );
  }
}

class _CalcCard extends StatelessWidget {
  final String label;
  final String value;
  final bool isTotal;

  const _CalcCard({
    required this.label,
    required this.value,
    this.isTotal = false,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: EdgeInsets.all(18),
      decoration: BoxDecoration(
        color: isTotal ? AppColors.ink : AppColors.surface,
        border: Border.all(
          color: isTotal ? AppColors.ink : AppColors.outline,
          width: 1,
        ),
        borderRadius: BorderRadius.circular(10),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Text(
            label,
            style: GoogleFonts.inter(
              fontSize: 11,
              letterSpacing: 0.1,
              color: isTotal
                  ? AppColors.background.withValues(alpha: 0.6)
                  : AppColors.inkFaint,
            ),
          ),
          SizedBox(height: 8),
          Text(
            value,
            style: GoogleFonts.fraunces(
              fontSize: 24,
              letterSpacing: -0.02,
              color: isTotal ? AppColors.background : AppColors.ink,
            ),
          ),
        ],
      ),
    );
  }
}

// --- TAX ALERT ---

class _TaxAlertSection extends StatelessWidget {
  final TaxAlert alert;

  const _TaxAlertSection({required this.alert});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: EdgeInsets.all(24),
      decoration: BoxDecoration(
        border: Border.all(
          color: AppColors.error.withValues(alpha: 0.35),
          width: 1,
        ),
        borderRadius: BorderRadius.circular(12),
        color: AppColors.error.withValues(alpha: 0.06),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Container(
            width: 40,
            height: 40,
            decoration: BoxDecoration(
              shape: BoxShape.circle,
              color: AppColors.error,
            ),
            alignment: Alignment.center,
            child: Text(
              '!',
              style: GoogleFonts.fraunces(
                fontSize: 18,
                color: AppColors.background,
              ),
            ),
          ),
          SizedBox(width: 20),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'Buyer\'s tax deduction at risk',
                  style: GoogleFonts.fraunces(
                    fontSize: 18,
                    fontWeight: FontWeight.w400,
                    color: AppColors.error,
                  ),
                ),
                SizedBox(height: 6),
                Text.rich(
                  TextSpan(
                    children: [
                      TextSpan(
                        text: 'Under ',
                        style: GoogleFonts.inter(
                          fontSize: 13,
                          color: AppColors.inkMuted,
                          height: 1.6,
                        ),
                      ),
                      TextSpan(
                        text: '§${alert.section}(h)',
                        style: GoogleFonts.jetBrainsMono(
                          fontSize: 12,
                          color: AppColors.error,
                          backgroundColor: AppColors.background,
                        ),
                      ),
                      TextSpan(
                        text:
                            ' of the Income Tax Act, payments to MSME vendors that exceed the statutory 45-day window are only deductible in the year actually paid. You can cite this when renegotiating.',
                        style: GoogleFonts.inter(
                          fontSize: 13,
                          color: AppColors.inkMuted,
                          height: 1.6,
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

// --- ACTION SECTION ---

class _ActionSection extends StatelessWidget {
  final String analysisId;
  final VoidCallback onDownloadPdf;

  const _ActionSection({
    required this.analysisId,
    required this.onDownloadPdf,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: EdgeInsets.only(top: 32),
      decoration: BoxDecoration(
        border: Border(
          top: BorderSide(color: AppColors.outline, width: 1),
        ),
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.start,
        children: [
          _SolidBtn(
            label: 'File grievance with MSEFC',
            onPressed: () => context.push('/analysis/$analysisId/grievance'),
          ),
          SizedBox(width: 12),
          _GhostBtn(
            label: 'Download PDF',
            onPressed: onDownloadPdf,
          ),
          SizedBox(width: 12),
          _GhostBtn(
            label: 'Share report',
            onPressed: () {
              final url = Uri.base
                  .resolve('/analysis/$analysisId/report')
                  .toString();
              Clipboard.setData(ClipboardData(text: url));
              ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(content: Text('Report link copied to clipboard')),
              );
            },
          ),
        ],
      ),
    );
  }
}

class _SolidBtn extends StatelessWidget {
  final String label;
  final VoidCallback onPressed;

  const _SolidBtn({required this.label, required this.onPressed});

  @override
  Widget build(BuildContext context) {
    return InkWell(
      onTap: onPressed,
      borderRadius: BorderRadius.circular(999),
      child: Container(
        padding: EdgeInsets.symmetric(horizontal: 18, vertical: 10),
        decoration: BoxDecoration(
          color: AppColors.ink,
          borderRadius: BorderRadius.circular(999),
        ),
        child: Text(
          label,
          style: GoogleFonts.inter(
            fontSize: 13,
            color: AppColors.background,
          ),
        ),
      ),
    );
  }
}

class _GhostBtn extends StatelessWidget {
  final String label;
  final VoidCallback onPressed;

  const _GhostBtn({required this.label, required this.onPressed});

  @override
  Widget build(BuildContext context) {
    return InkWell(
      onTap: onPressed,
      borderRadius: BorderRadius.circular(999),
      child: Container(
        padding: EdgeInsets.symmetric(horizontal: 18, vertical: 10),
        decoration: BoxDecoration(
          color: Colors.transparent,
          border: Border.all(color: AppColors.outline, width: 1),
          borderRadius: BorderRadius.circular(999),
        ),
        child: Text(
          label,
          style: GoogleFonts.inter(
            fontSize: 13,
            color: AppColors.ink,
          ),
        ),
      ),
    );
  }
}
